version: 2
jobs:

  php-80:
    docker:
      - image: cimg/php:8.0
    steps:
      - checkout
      - restore_cache:
          keys:
            - php8.0-{{ .Branch }}
      - run: composer require phpunit/phpunit
      - run: php vendor/phpunit/phpunit/phpunit
      - save_cache:
          key: php8.0-{{ .Branch }}
          paths:
            - /root/.cache/composer

  php-81:
    docker:
      - image: cimg/php:8.1
    steps:
      - checkout
      - restore_cache:
          keys:
            - php8.1-{{ .Branch }}
      - run: composer require phpunit/phpunit
      - run: php vendor/phpunit/phpunit/phpunit
      - save_cache:
          key: php8.1-{{ .Branch }}
          paths:
            - /root/.cache/composer

workflows:
  version: 2
  build-test-all:
    jobs:
      - php-80
      - php-81
