version: 2
jobs:
  php-71:
    docker:
      - image: circleci/php:7.1
    steps:
      - checkout
      - restore_cache:
          keys:
            - source-php7.1-{{ .Branch }}-{{ .Revision }}
            - source-php7.1-{{ .Branch }}-
            - source-php7.1-
      - run: composer require phpunit/phpunit infection/infection squizlabs/php_codesniffer
      - run: mkdir -p coverage
      - run: php vendor/phpunit/phpunit/phpunit --coverage-html coverage --coverage-clover=coverage.clover
      - run: php vendor/infection/infection/bin/infection
      - run: cat infection.log
      - run: php vendor/squizlabs/php_codesniffer/bin/phpcs src | tee codesniff.log
      - run: php examples/support.php
      - run: wget https://scrutinizer-ci.com/ocular.phar
      - run: php ocular.phar code-coverage:upload --format=php-clover coverage.clover
      - save_cache:
          key: source-php7.1-{{ .Branch }}-{{ .Revision }}
          paths:
            - vendor
      - store_artifacts:
          path: coverage
      - store_artifacts:
          path: infection.log
      - store_artifacts:
          path: codesniff.log

  php-72:
    docker:
      - image: circleci/php:7.2
    steps:
      - checkout
      - restore_cache:
          keys:
            - source-php7.2-{{ .Branch }}-{{ .Revision }}
            - source-php7.2-{{ .Branch }}-
            - source-php7.2-
      - run: composer require phpunit/phpunit
      - run: php vendor/phpunit/phpunit/phpunit
      - save_cache:
          key: source-php7.2-{{ .Branch }}-{{ .Revision }}
          paths:
            - vendor

  php-73:
    docker:
      - image: circleci/php:7.3
    steps:
      - checkout
      - restore_cache:
          keys:
            - source-php7.3-{{ .Branch }}-{{ .Revision }}
            - source-php7.3-{{ .Branch }}-
            - source-php7.3-
      - run: composer require phpunit/phpunit
      - run: php vendor/phpunit/phpunit/phpunit
      - save_cache:
          key: source-php7.3-{{ .Branch }}-{{ .Revision }}
          paths:
            - vendor
        
workflows:
  version: 2
  build-test-all:
    jobs:
      - php-71
      - php-72
      - php-73
