version: 2

aliases:
  - &composer
    name: Install phpunit
    command: composer require phpunit/phpunit

jobs:
  php-71:
    docker:
      - image: cimg/php:7.1
    steps:
      - checkout
      - restore_cache:
          keys:
            - php7.1-{{ .Branch }}
      - run: *composer
      - run: ./vendor/bin/phpunit
      - save_cache:
          key: php7.1-{{ .Branch }}
          paths: &paths
            - vendor
            - composer.lock

  php-72:
    docker:
      - image: cimg/php:7.2
    steps:
      - checkout
      - restore_cache:
          keys:
            - php7.2-{{ .Branch }}
      - run: *composer
      - run: ./vendor/bin/phpunit
      - save_cache:
          key: php7.2-{{ .Branch }}
          paths: *paths

  php-73:
    docker:
      - image: cimg/php:7.3
    steps:
      - checkout
      - restore_cache:
          keys:
            - php7.3-{{ .Branch }}
      - run: *composer
      - run: ./vendor/bin/phpunit
      - save_cache:
          key: php7.3-{{ .Branch }}
          paths: *paths

  php-74:
    docker:
      - image: cimg/php:7.4
    steps:
      - checkout
      - restore_cache:
          keys:
            - php7.4-{{ .Branch }}
      - run: *composer
      - run: ./vendor/bin/phpunit
      - save_cache:
          key: php7.4-{{ .Branch }}
          paths: *paths

  php-80:
    docker:
      - image: cimg/php:8.0
    steps:
      - checkout
      - restore_cache:
          keys:
            - php8.0-{{ .Branch }}
      - run: *composer
      - run: ./vendor/bin/phpunit
      - save_cache:
          key: php8.0-{{ .Branch }}
          paths: *paths

  php-81:
    docker:
      - image: cimg/php:8.1
    steps:
      - checkout
      - restore_cache:
          keys:
            - php8.1-{{ .Branch }}
      - run: *composer
      - run: ./vendor/bin/phpunit
      - save_cache:
          key: php8.1-{{ .Branch }}
          paths: *paths

  php-82:
    docker:
      - image: cimg/php:8.2
    steps:
      - checkout
      - restore_cache:
          keys:
            - php8.2-{{ .Branch }}
      - run: *composer
      - run: ./vendor/bin/phpunit
      - save_cache:
          key: php8.2-{{ .Branch }}
          paths: *paths

workflows:
  version: 2
  build-test-all:
    jobs:
      - php-71
      - php-72
      - php-73
      - php-74
      - php-80
      - php-81
      - php-82
